# Generated by Django 4.2.7 on 2026-06-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_m2m_relations_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professeurfilieres',
            options={'managed': False, 'verbose_name': 'Relation Professeur-Filière', 'verbose_name_plural': 'Relations Professeur-Filières'},
        ),
    ]
